  zencrepes_prod:
    image: fgerthoffert/zencrepes
    ports:
      - "8000:3000"
    links:
      - mongo_prod
    environment:
      - ROOT_URL=https://zencrepes.io
      - STARTUP_DELAY=20
      - DISABLE_WEBSOCKETS=1
      - METEOR_SETTINGS=$PROD_METEOR_SETTINGS
      - MONGO_URL=mongodb://mongo_prod:27017/meteor

  mongo_prod:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger

