  zencrepes:
    image: fgerthoffer/zencrepes
    ports:
      - "8000:3000"
    links:
      - mongo
    environment:
      - ROOT_URL=https://zencrepes.io
      - STARTUP_DELAY=20
      - METEOR_SETTINGS=$METEOR_SETTINGS
      - MONGO_URL=mongodb://mongo:27017/meteor

  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger

