  zencrepes_dev:
    image: fgerthoffer/zencrepes
    ports:
      - "9000:3000"
    links:
      - mongo_dev
    environment:
      - ROOT_URL=https://dev.zencrepes.io
      - STARTUP_DELAY=20
      - METEOR_SETTINGS=$METEOR_SETTINGS
      - MONGO_URL=mongodb://mongo:27117/meteor

  mongo_dev:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    ports:
      - "27117:27017"

